server:
  port: 8083
  servlet:
    encoding:
      force-response: true

logging:
  level:
    kr.study.jpa1: trace
    #kr.study.jpa1.controller: trace

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/basicjpa?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  thymeleaf:
    prefix: classpath:/templates/

  jpa:
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update

    # JDBC TimeZone Setting
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        format_sql: true
        use_sql_comments: true

